// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_xsKX63li5qIYe4mnQ1HatKIgFK-wEYA',
    appId: '1:781773518874:web:41d4eec815d669ff9139a3',
    messagingSenderId: '781773518874',
    projectId: 'awesome-notes-dcf59',
    authDomain: 'awesome-notes-dcf59.firebaseapp.com',
    storageBucket: 'awesome-notes-dcf59.appspot.com',
    measurementId: 'G-0XQBPL6MX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB058_GUsaxXKWtCinrE_Wv8vnO6LDEqF8',
    appId: '1:781773518874:android:025dcd113a5b676a9139a3',
    messagingSenderId: '781773518874',
    projectId: 'awesome-notes-dcf59',
    storageBucket: 'awesome-notes-dcf59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvkHJJUZUTs8P1OeUCBKtl7CWloMZ1oro',
    appId: '1:781773518874:ios:59aa44cb7cd9c65a9139a3',
    messagingSenderId: '781773518874',
    projectId: 'awesome-notes-dcf59',
    storageBucket: 'awesome-notes-dcf59.appspot.com',
    iosBundleId: 'com.example.demoFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvkHJJUZUTs8P1OeUCBKtl7CWloMZ1oro',
    appId: '1:781773518874:ios:a1dd061dd3f25f539139a3',
    messagingSenderId: '781773518874',
    projectId: 'awesome-notes-dcf59',
    storageBucket: 'awesome-notes-dcf59.appspot.com',
    iosBundleId: 'com.example.demoFrontend.RunnerTests',
  );
}
